### ISSUE TITLE
replace Realtime API + Drive with Postgres storage

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition#477]
## Stage 1: Run duplicate Postgres storage in background

- [x] Save to realtime, drive and postgres, but don't change loading code.
- [x] Save to Postgres in Markdown - two text columns (qdl + notes)
  - [x] Double buffered save (2 rows, saves write the oldest row if both older than 24h, otherwise most recent row)

Key Result: Monitor for a while to make sure infra and code is stable, and that DB storage use isn't utterly insane (which it shouldn't be, since a single quest should only take one row / overwrite it)

## Stage 2 (Dec 11): Switch to loading contents from Postgres by default, but still open files from Drive

- [x] Fall back to realtime, then to loading from drive file if postgres load fails
- [x] Keep front-end code structured as realtime change manager to make it easier to re-add realtime later

## Stage 3 (Dec 11): Turn off realtime

- [x] get rid of writing to realtime (so we'll need to educate about new filesystem + loss of realtime collaboration)
- [x] Add start-of-edit timestamp to questdata when loaded, prevent user with different timestamp from editing the file and indicate in the UI (require a refresh).

## Notes

- we'll still have to support loading files from Drive + content from Realtime API for the foreseeable future
